name: Rolebook Local
values:
  - key: baseUrl
    value: 'http://localhost:3000/api'
  - key: token
    value: ''
  - key: userId
    value: ''
  - key: verifyEmail
    value: ''
  - key: campaignId
    value: ''
  - key: sessionId
    value: ''
  - key: playerId
    value: ''
  - key: itemId
    value: ''
  - key: spellId
    value: ''
  - key: arsenalSpellId
    value: ''
  - key: arsenalEquipmentId
    value: ''
  - key: customEquipmentId
    value: ''
  - key: customSpellId
    value: ''
  - key: avatarUploadUrl
    value: ''
  - key: avatarKey
    value: ''
