name: Rolebook Local
values:
  - key: baseUrl
    value: 'http://localhost:3000/api'
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: userId
    value: ''
    enabled: true
  - key: campaignId
    value: ''
    enabled: true
  - key: sessionId
    value: ''
    enabled: true
  - key: playerId
    value: ''
    enabled: true
  - key: itemId
    value: ''
    enabled: true
  - key: spellId
    value: ''
    enabled: true
  - key: arsenalSpellId
    value: ''
    enabled: true
  - key: arsenalEquipmentId
    value: ''
    enabled: true
  - key: customEquipmentId
    value: ''
    enabled: true
  - key: customSpellId
    value: ''
    enabled: true
